### ISSUE TITLE
Googe Mail Notification

### ISSUE THREAD

**Issue by KZeronimo** [todbot/Blink1Control2#35]
I have the following event source setup but I've never seen it fire despite getting emails into my primary inbox from the specified sender

![image](https://cloud.githubusercontent.com/assets/21271446/20670557/5fae2704-b547-11e6-860a-d54479ae8549.png)

Thoughts?

**Comment by waynearthurtondidata** [comment]
I experimented for a very long time and found that even though the config screen shows imap it might be stored as Gmail in the config.  I changed back to Gmail and then to IMAP and it worked!  You could also check your config file and make sure that IMAP is the account type.

**Comment by warthurton** [comment]
I experimented for a very long time and found that even though the config screen shows imap it might be stored as Gmail in the config. I changed back to Gmail and then to IMAP and it worked! You could also check your config file and make sure that IMAP is the account type.

**Comment by KZeronimo** [comment]
This fixed the issue - thanks for your help
